#!/usr/bin/env bash

###################################### HELLO THIS IS IMPORTANT ######################################
### When the script end, immediately after OMZ installs... DO NOT EXIT ZSH.
### Please run the post install script
#####################################################################################################

PACKAGES=(
    "arch-install-scripts"
    "base"
    "base-devel"
    "eza"
    "fakeroot-tcp"
    "git"
    "github-cli"
    "glow"
    "go"
    "lazygit"
    "less"
    "lf"
    "lua"
    "nano"
    "neovim"
    "npm"
    "python"
    "python-pynvim"
    "rust"
    "stylua"
    "sudo"
    "unzip"
    "vim"
    "rust"
    "zoxide"
    "zsh"
)

### install yay first
cd ~ # make sure we're in home dir
if command -v "yay" &>/dev/null; then
    echo "yay is installed..."
else
    sudo pacman -S --needed git base-devel && git clone https://aur.archlinux.org/yay.git && cd yay && makepkg -si
fi

### compare PACKAGES with what's been installed so far,
### only install what hasn't been installed yet
installed_packages=$(pacman -Qe | awk '{print $1}')
to_install=()
for package in "${PACKAGES[@]}"; do
    if ! echo "$installed_packages" | grep -q "^$package$"; then
        to_install+=("$package")
    else
        echo "Installed... skipping: $package"
    fi
done
yay -S ${to_install[@]}
rm -rf ~/yay

### start cloning some repos
mkdir -p ~/Documents/Github
cd ~/Documents/Github

# these repos are all public, we set git creds later
git clone https://github.com/vague2k/huez.nvim.git
git clone https://github.com/vague2k/vague.nvim.git
git clone https://github.com/vague2k/rummage.git
git clone https://github.com/vague2k/smv.git
git clone https://github.com/vague2k/dotfiles.git

# make dotfile symlinks
cd ~/Documents/Github/dotfiles
chmod +x ./mklinks && ./mklinks

# setup zsh
cd ~/Documents/Github/dotfiles/zsh

sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended

# move the omz dir and clean up
# FIXME: scripts kinda falls flat here.
zsh -c "mv ~/.oh-my-zsh ./ohmyzsh; rm -rf ~/.oh-my-zsh; cp .zshenv ~/.zshenv; source ~/.zshenv; source ./.zshrc; rm ~/.bash*; rm ~/.shell*; rm ~/.z*"

# set git creds
gh auth login

git config --global user.name "vague2k"
git config --global user.email "ilovedrawing056@gmail.com"

echo ""
echo "Everything is setup! Make sure to fully restart the terminal just in case."
echo "You may or may not need to relogin/reset git credentials into git"
echo ""
