#!/usr/bin/env bash

mv ~/.oh-my-zsh ./ohmyzsh
rm -rf ~/.oh-my-zsh

cp .zshenv ~/.zshenv
source ~/.zshenv
source ./.zshrc

rm ~/.bash*
rm ~/.shell*
rm ~/.zcompdump*
rm ~/.zshrc

# set git creds
gh auth login

git config --global user.name "vague2k"
git config --global user.email "ilovedrawing056@gmail.com"
