[general]
framerate = 60
bars = 15
autosens = 1
lower_cutoff_freq = 100
higher_cutoff_freq = 20000

[input]
method = pipewire
source = auto

[output]
method = raw
raw_target = /dev/stdout
data_format = ascii
ascii_max_range = 1000
bar_delimiter = 59
frame_delimiter = 10
channels = mono

[smoothing]
noise_reduction = 77
monstercat = 1
