hl.on("hyprland.start", function()
  hl.exec_cmd("qs")
  -- Polkit authentication agent (package: hyprpolkitagent)
  hl.exec_cmd("systemctl --user start hyprpolkitagent")
  -- Wallpaper daemon (package: awww)
  hl.exec_cmd("awww-daemon")
end)
